apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  MYSQL_DATABASE: "nextcloud"
  NEXTCLOUD_TRUSTED_DOMAINS: "*.azurewebsites.net nextcloud.example.com"
  REDIS_HOST: "redis"
  REDIS_HOST_PORT: "6379"
  PHP_MEMORY_LIMIT: "512M"
  PHP_UPLOAD_LIMIT: "10G"
